### ISSUE TITLE
openocd build error for macOS 

### ISSUE THREAD

**Issue by Dracanrage** [majbthrd/pico-debug#10]
I have referred to the #5, but it didn't work for me.
After used that commands, it shows the `error: hidapi is required for the CMSIS-DAP Compliant Debugger` as before.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118816899-3cae2780-b8e5-11eb-90dd-342131735a0e.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118816929-45066280-b8e5-11eb-9411-10395b5eb4ba.png">

**Comment by majbthrd** [comment]
Note that the first screenshot shows:

`
checking for hidapi... no
`

which implies the steps prescribed in #5 didn't happen properly.  I have to wonder whether your "export" commands in the second screenshot may not have created the environmental variables.  You can run "export" without arguments to see what HIDAPI_LIBS and PKG_CONFIG_PATH got set to.

@citizenfish, would you be able to provide any insight?  I am not a Mac user.  Thanks.

**Comment by citizenfish** [comment]
I have edited my instructions which may be causing this issue.

Run ./bootstrap then ./configure --enable-static --disable-shared

But as @majbthrd said we need to see the output of export after the two commands you should see something like this:-

```
declare -x PKG_CONFIG_PATH="/Users/daveb/dev/scratch/hidapi/pc"
declare -x HIDAPI_LIBS="-L/Users/daveb/dev/scratch/hidapi/mac/.libs -lhidapi"
```
And be able to list the two directories with ls

**Comment by Dracanrage** [comment]
> I have edited my instructions which may be causing this issue.
> 
> Run ./bootstrap then ./configure --enable-static --disable-shared
> 
> But as @majbthrd said we need to see the output of export after the two commands you should see something like this:-
> 
> ```
> declare -x PKG_CONFIG_PATH="/Users/daveb/dev/scratch/hidapi/pc"
> declare -x HIDAPI_LIBS="-L/Users/daveb/dev/scratch/hidapi/mac/.libs -lhidapi"
> ```
> 
> And be able to list the two directories with ls

<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118841266-bf8dad00-b8fa-11eb-9ae4-78d96812f1d2.png">
I use echo and get this, but I didn't see like `declare ......`

**Comment by Dracanrage** [comment]
After I use 
```
declare -x PKG_CONFIG_PATH="/Users/mac/openocd/hidapi/pc"
declare -x HIDAPI_LIBS="-L/Users/mac/openocd/hidapi/mac/.libs -lhidapi"
```
It didn't work as well
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118841931-55293c80-b8fb-11eb-857f-09452ce53de9.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118841971-5ce8e100-b8fb-11eb-8bbc-97f24b8886e0.png">

**Comment by majbthrd** [comment]
@Dracanrage, "declare" is not a shell command.  If you scroll back, you will see that @citizenfish stated this what you should see output after the "export" command.

@Dracanrage, you have not showed a screenshot of following the #5 instructions for building hidapi where "./configure --enable-static --disable-shared" is used.

**Comment by Dracanrage** [comment]
> @Dracanrage, "declare" is not a shell command. If you scroll back, you will see that @citizenfish stated this what you should see output after the "export" command.
> 
> @Dracanrage, you have not showed a screenshot of following the #5 instructions for building hidapi where "./configure --enable-static --disable-shared" is used.
@majbthrd 
Sorry, I'm in the different time zone, I just read the response before.
1. git clone https://github.com/signal11/hidapi.git
<img width="532" alt="image" src="https://user-images.githubusercontent.com/30333935/118960822-3d52c680-b996-11eb-9698-e8672f484130.png">
2. cd hidapi
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118960860-4ba0e280-b996-11eb-81b9-92a4cdcc39e9.png">
3. ./bootstrap
then I get this:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118960947-5eb3b280-b996-11eb-96b5-512704ea7e5d.png">
if I use the hidapi from libusb/hidapi, I get this:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118961149-94589b80-b996-11eb-9b6c-18360f0f2a42.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118961199-a63a3e80-b996-11eb-82ba-71ceb7828cdb.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118961215-aa665c00-b996-11eb-8855-bbbec361f723.png">
It looks well now.
4. ./configure --enable-static --disable-shared
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118961944-73dd1100-b997-11eb-998b-743fe0971b2d.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118961963-77709800-b997-11eb-8b93-977ed7d816f0.png">
5. make
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118962051-8d7e5880-b997-11eb-9c69-d525c9d0f98f.png">
6. export HIDAPI_LIBS="-L`pwd`/mac/.libs -lhidapi" and export PKG_CONFIG_PATH="`pwd`/pc"
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118962118-a0912880-b997-11eb-843a-9ed130c5856a.png">
I know @citizenfish says will see some thing like this:
```
declare -x PKG_CONFIG_PATH="/Users/daveb/dev/scratch/hidapi/pc"
declare -x HIDAPI_LIBS="-L/Users/daveb/dev/scratch/hidapi/mac/.libs -lhidapi"
```
But I didn't see anything, so I tried them as shell commands to figure out whether it could be used.
7. ./configure --enable-cmsis-dap CFLAGS="-Wno-deprecated -Wno-strict-prototypes"
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118962568-172e2600-b998-11eb-8f1f-8c2a7b6eaf41.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118962584-1b5a4380-b998-11eb-9d16-3ae51e76aa9f.png">
Then it crashed as I said.

**Comment by citizenfish** [comment]
It looks to me like you may be this stage wrong by pasting in both commands at once

<img width="634" alt="Screenshot 2021-05-20 at 11 28 27" src="https://user-images.githubusercontent.com/10531204/118963653-90a92280-b95e-11eb-9cd8-1d9e8a96fcf9.png">

Follow these instructions:-

1) enter the command below then press return
```
export HIDAPI_LIBS="-L`pwd`/mac/.libs -lhidapi"
```
2) enter the command below then press return
```
export PKG_CONFIG_PATH="`pwd`/pc"
```
3) enter this command then press return
```
ls $PKG_CONFIG_PATH
```

You should see a directory listing, if not enter this command then press return and show us the result

```
echo $PKG_CONFIG_PATH
```

**Comment by Dracanrage** [comment]
I have seen the directory as below:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/30333935/118966195-0da6bd00-b99c-11eb-86a3-53773aef1706.png">
But when I use 

```
./configure --enable-cmsis-dap CFLAGS="-Wno-deprecated -Wno-strict-prototypes"
```
It still didn't work:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118966311-3038d600-b99c-11eb-8d08-8810814a7059.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30333935/118966421-4e063b00-b99c-11eb-827a-3577abba6fa9.png">

**Comment by majbthrd** [comment]
Doing a web search for “macos openocd cmsis-dap hid” yields this:

https://gist.github.com/technobly/f2c14eaa7334db80849d45614250bdf0

The author's instructions call for setting the paths in the same line as part of the configure call, and the author writes "Seems gross to copy the path directly, but trust me it doesn't work unless you do".

Please understand that I am NOT SUGGESTING that you copy and paste the instructions exactly as-is, but perhaps this might suggest a path for you to explore for the problem with your particular Mac.

**Comment by Dracanrage** [comment]
> Doing a web search for “macos openocd cmsis-dap hid” yields this:
> 
> https://gist.github.com/technobly/f2c14eaa7334db80849d45614250bdf0
> 
> The author's instructions call for setting the paths in the same line as part of the configure call, and the author writes "Seems gross to copy the path directly, but trust me it doesn't work unless you do".
> 
> Please understand that I am NOT SUGGESTING that you copy and paste the instructions exactly as-is, but perhaps this might suggest a path for you to explore for the problem with your particular Mac.

Thanks! I finally find the problem:
The hombrew didn't really install the pkg-config package which openocd required.
Just try:

```
brew reinstall pkg-config
``` 

Then re-configure, all will be fine.
