### ISSUE TITLE
Does it work for pico-w ? How to build pico-debug for pico W board?

### ISSUE THREAD

**Issue by darowny** [majbthrd/pico-debug#28]
Does built release .uf2 work for the new pico W board?
Seems like it doesn't ? 

Maybe I am setting up launch.json incorrectly ? Maybe I should install something ?
```Launching GDB: arm-none-eabi-gdb -q --interpreter=mi2
1-gdb-version
Could not start GDB process, does the program exist in filesystem?
Error: spawn arm-none-eabi-gdb ENOENT
```

Manually running after copying .uf2 release of pico-debug gives this: 
```openocd -f board/pico-debug.cfg```
```
Open On-Chip Debugger 0.12.0-rc2+dev-00028-g9501b263e (2022-12-11-17:34)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Warn : rp2040-core0.cfg configuration file is deprecated and will be
       removed in the next release. Use following parameters instead:
          -c 'set USE_CORE 0' -f target/rp2040.cfg
cortex_m reset_config sysresetreq

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: unable to open CMSIS-DAP device 0x1209:0x2488
Error: unable to find a matching CMSIS-DAP device
```

**Comment by majbthrd** [comment]
I do not have a pico W board to try.

If you are using Linux (you don't bother to say what OS or what software you are using... you just say "launch.json" as if that means something), try this:

Copy .uf2 of pico-debug to Pico, and then run:

lsusb

and report back what its output is.  You are looking for a 1209:2488 device in the list.

If you are running Windows, after copying the .uf2, open Device Manager and look for the 1209:2488 device.
