### ISSUE TITLE
a small typo in a otherwise extremely good project

### ISSUE THREAD

**Issue by kangsenlu** [majbthrd/pico-debug#4]
$ cd ~/pico/pico-examples/build/picoboard/blinky
$ gdb-multiarch picoboard-blinky.elf

In the above gdb-multiarch command, the elf file name should contain "_", not "-".

In addition, the application must be built before the openocd is built and gdb is started.

Thanks for the good work.

**Comment by majbthrd** [comment]
Thank you!  I've made a correction.
